---
title: "Mixed Effects Models and other notes from the session"
author: "Lukas Schmid"
date: "9 1 2020"
output:
  html_document:
    toc_float: TRUE
    code_folding: hide
---

# exams

## example code

- everybody got the best grade

## 48-hours exam

### formalities
- we have to send in five pages (PDF)
- Henrik will not read the any more pages
- we will be sent the code at 10:00 on Saturday, 1st of March
- we have to send the code back until 10:00 on Monday, 3rd of March
- there will be an additional 5% on the grade for writing a  [Haiku](https://ja.wikipedia.org/wiki/%E4%BF%B3%E5%8F%A5) about the data
- our task is to find the most important patterns of the data, "What is the
most important message in the data?"
- there will be different datasets (four to nine) which everyone of us will be
assigned to (groups of three to four people)

> I never said you should work together. But it would be stupid not to. *(Henrik von Werden)*

### content and structure
- tests can be used, but we do not have to explain how they work statistically
- how to structure the code
  - tell a story about the data!
  - Chan suggests to look at Lukas S.'s code about the treering-datasets: 
  communicate what questions you have asked yourself when you looked at the 
  code
  
### evaluation criteria that Henrik
- steps of analysis that do not contribute to (one of the) question(s) that 
were posed will be counted towards a bad evaluation

# writing code coherently

- some code was well explained, other not so much
- we need a way to make sure that shared code works on different machines:
  - **send the plain code (.R or .Rmd)** and a **PDF generated from R Markdown**
  - additionally, everyone can send the report in any other format (e.g. .html)
    for more interactive documents
- we need a common way of how to structure code
  - general starting point: nature of the dataset, descriptive statistics,
  formulate assumptions and main questions (Henriks ideal number for research
  question is five)
  - focus on specifics that help you answer your question

# 

# Mixed Effects Models